// hello
const HELLO = "HELLO";
const HELLO_SUCCESS = "HELLO_SUCCESS";
const HELLO_FAILS = "HELLO_FAILS";
// reverser
const REVERSE = "REVERSE";
const REVERSE_SUCCESS = "REVERSE_SUCCESS";
const REVERSE_FAILS = "REVERSE_FAILS";
// todo
// C
const CREATE_TODO = "CREATE_TODO";
const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
const CREATE_TODO_FAILS = "CREATE_TODO_FAILS";
// R
const FETCH_TODO = "FETCH_TODO";
const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
const FETCH_TODO_FAILS = "FETCH_TODO_FAILS";
// U
const UPDATE_TODO = "UPDATE_TODO";
const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
const UPDATE_TODO_FAILS = "UPDATE_TODO_FAILS";
// D
const DELETE_TODO = "DELETE_TODO";
const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
const DELETE_TODO_FAILS = "DELETE_TODO_FAILS";
// todo items
// C
const CREATE_TODO_ITEM = "CREATE_TODO_ITEM";
const CREATE_TODO_ITEM_SUCCESS = "CREATE_TODO_ITEM_SUCCESS";
const CREATE_TODO_ITEM_FAILS = "CREATE_TODO_ITEM_FAILS";
// R
const FETCH_TODO_ITEM = "FETCH_TODO_ITEM";
const FETCH_TODO_ITEM_SUCCESS = "FETCH_TODO_ITEM_SUCCESS";
const FETCH_TODO_ITEM_FAILS = "FETCH_TODO_ITEM_FAILS";
// U
const UPDATE_TODO_ITEM = "UPDATE_TODO_ITEM";
const UPDATE_TODO_ITEM_SUCCESS = "UPDATE_TODO_ITEM_SUCCESS";
const UPDATE_TODO_ITEM_FAILS = "UPDATE_TODO_ITEM_FAILS";
// D
const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
const DELETE_TODO_ITEM_SUCCESS = "DELETE_TODO_ITEM_SUCCESS";
const DELETE_TODO_ITEM_FAILS = "DELETE_TODO_ITEM_FAILS";

export {
    HELLO, HELLO_SUCCESS, HELLO_FAILS,

    REVERSE, REVERSE_SUCCESS, REVERSE_FAILS,

    CREATE_TODO, CREATE_TODO_SUCCESS, CREATE_TODO_FAILS,
    FETCH_TODO, FETCH_TODO_SUCCESS, FETCH_TODO_FAILS,
    UPDATE_TODO, UPDATE_TODO_SUCCESS, UPDATE_TODO_FAILS,
    DELETE_TODO, DELETE_TODO_SUCCESS, DELETE_TODO_FAILS,

    CREATE_TODO_ITEM, CREATE_TODO_ITEM_SUCCESS, CREATE_TODO_ITEM_FAILS,
    FETCH_TODO_ITEM, FETCH_TODO_ITEM_SUCCESS, FETCH_TODO_ITEM_FAILS,
    UPDATE_TODO_ITEM, UPDATE_TODO_ITEM_SUCCESS, UPDATE_TODO_ITEM_FAILS,
    DELETE_TODO_ITEM, DELETE_TODO_ITEM_SUCCESS, DELETE_TODO_ITEM_FAILS
}
